scoreboard players operation @s bb.dd.state = #state.close bb.dd.enum

function boomber:double_door/[variant]/method/get_info

execute if score #hinge bb.dd.var = #hinge.left bb.dd.enum if score #facing bb.dd.var = #facing.east bb.dd.enum positioned ~ ~ ~1 if block ~ ~ ~ minecraft:[variant][hinge=right, facing=east, half=lower, open=true] as @e[type=area_effect_cloud, tag=boomber.double_door.[variant], distance=..0.3] at @s run function boomber:double_door/[variant]/method/close
execute if score #hinge bb.dd.var = #hinge.left bb.dd.enum if score #facing bb.dd.var = #facing.west bb.dd.enum positioned ~ ~ ~-1 if block ~ ~ ~ minecraft:[variant][hinge=right, facing=west, half=lower, open=true] as @e[type=area_effect_cloud, tag=boomber.double_door.[variant], distance=..0.3] at @s run function boomber:double_door/[variant]/method/close
execute if score #hinge bb.dd.var = #hinge.left bb.dd.enum if score #facing bb.dd.var = #facing.north bb.dd.enum positioned ~1 ~ ~ if block ~ ~ ~ minecraft:[variant][hinge=right, facing=north, half=lower, open=true] as @e[type=area_effect_cloud, tag=boomber.double_door.[variant], distance=..0.3] at @s run function boomber:double_door/[variant]/method/close
execute if score #hinge bb.dd.var = #hinge.left bb.dd.enum if score #facing bb.dd.var = #facing.south bb.dd.enum positioned ~-1 ~ ~ if block ~ ~ ~ minecraft:[variant][hinge=right, facing=south, half=lower, open=true] as @e[type=area_effect_cloud, tag=boomber.double_door.[variant], distance=..0.3] at @s run function boomber:double_door/[variant]/method/close

execute if score #hinge bb.dd.var = #hinge.right bb.dd.enum if score #facing bb.dd.var = #facing.east bb.dd.enum positioned ~ ~ ~-1 if block ~ ~ ~ minecraft:[variant][hinge=left, facing=east, half=lower, open=true] as @e[type=area_effect_cloud, tag=boomber.double_door.[variant], distance=..0.3] at @s run function boomber:double_door/[variant]/method/close
execute if score #hinge bb.dd.var = #hinge.right bb.dd.enum if score #facing bb.dd.var = #facing.west bb.dd.enum positioned ~ ~ ~1 if block ~ ~ ~ minecraft:[variant][hinge=left, facing=west, half=lower, open=true] as @e[type=area_effect_cloud, tag=boomber.double_door.[variant], distance=..0.3] at @s run function boomber:double_door/[variant]/method/close
execute if score #hinge bb.dd.var = #hinge.right bb.dd.enum if score #facing bb.dd.var = #facing.north bb.dd.enum positioned ~-1 ~ ~ if block ~ ~ ~ minecraft:[variant][hinge=left, facing=north, half=lower, open=true] as @e[type=area_effect_cloud, tag=boomber.double_door.[variant], distance=..0.3] at @s run function boomber:double_door/[variant]/method/close
execute if score #hinge bb.dd.var = #hinge.right bb.dd.enum if score #facing bb.dd.var = #facing.south bb.dd.enum positioned ~1 ~ ~ if block ~ ~ ~ minecraft:[variant][hinge=left, facing=south, half=lower, open=true] as @e[type=area_effect_cloud, tag=boomber.double_door.[variant], distance=..0.3] at @s run function boomber:double_door/[variant]/method/close